export const PRESIDENTS_BY_STATE = {
  'Arkansas': [
    { name: 'Bill Clinton', number: 42, years: '1993–2001', party: 'Democrat', born: 'Hope, AR' },
  ],
  'California': [
    { name: 'Richard Nixon', number: 37, years: '1969–1974', party: 'Republican', born: 'Yorba Linda, CA' },
    { name: 'Herbert Hoover', number: 31, years: '1929–1933', party: 'Republican', born: 'West Branch, IA (raised in CA)' },
  ],
  'Connecticut': [
    { name: 'George W. Bush', number: 43, years: '2001–2009', party: 'Republican', born: 'New Haven, CT' },
  ],
  'Georgia': [
    { name: 'Jimmy Carter', number: 39, years: '1977–1981', party: 'Democrat', born: 'Plains, GA' },
  ],
  'Hawaii': [
    { name: 'Barack Obama', number: 44, years: '2009–2017', party: 'Democrat', born: 'Honolulu, HI' },
  ],
  'Illinois': [
    { name: 'Barack Obama', number: 44, years: '2009–2017', party: 'Democrat', born: 'Honolulu, HI (represented IL)' },
    { name: 'Ronald Reagan', number: 40, years: '1981–1989', party: 'Republican', born: 'Tampico, IL' },
    { name: 'Abraham Lincoln', number: 16, years: '1861–1865', party: 'Republican', born: 'Hodgenville, KY (represented IL)' },
    { name: 'Ulysses S. Grant', number: 18, years: '1869–1877', party: 'Republican', born: 'Point Pleasant, OH (represented IL)' },
  ],
  'Iowa': [
    { name: 'Herbert Hoover', number: 31, years: '1929–1933', party: 'Republican', born: 'West Branch, IA' },
  ],
  'Kansas': [
    { name: 'Dwight D. Eisenhower', number: 34, years: '1953–1961', party: 'Republican', born: 'Denison, TX (raised in Abilene, KS)' },
  ],
  'Kentucky': [
    { name: 'Abraham Lincoln', number: 16, years: '1861–1865', party: 'Republican', born: 'Hodgenville, KY' },
    { name: 'Zachary Taylor', number: 12, years: '1849–1850', party: 'Whig', born: 'Barboursville, VA (raised in KY)' },
  ],
  'Massachusetts': [
    { name: 'John F. Kennedy', number: 35, years: '1961–1963', party: 'Democrat', born: 'Brookline, MA' },
    { name: 'John Adams', number: 2, years: '1797–1801', party: 'Federalist', born: 'Braintree, MA' },
    { name: 'John Quincy Adams', number: 6, years: '1825–1829', party: 'Democratic-Republican', born: 'Braintree, MA' },
    { name: 'George H.W. Bush', number: 41, years: '1989–1993', party: 'Republican', born: 'Milton, MA' },
    { name: 'Calvin Coolidge', number: 30, years: '1923–1929', party: 'Republican', born: 'Plymouth, VT (associated with MA)' },
  ],
  'Missouri': [
    { name: 'Harry S. Truman', number: 33, years: '1945–1953', party: 'Democrat', born: 'Lamar, MO' },
    { name: 'Ulysses S. Grant', number: 18, years: '1869–1877', party: 'Republican', born: 'Point Pleasant, OH (raised in MO)' },
  ],
  'Nebraska': [
    { name: 'Gerald Ford', number: 38, years: '1974–1977', party: 'Republican', born: 'Omaha, NE' },
  ],
  'New Hampshire': [
    { name: 'Franklin Pierce', number: 14, years: '1853–1857', party: 'Democrat', born: 'Hillsborough, NH' },
  ],
  'New Jersey': [
    { name: 'Grover Cleveland', number: 22 & 24, years: '1885–1889 & 1893–1897', party: 'Democrat', born: 'Caldwell, NJ' },
    { name: 'Woodrow Wilson', number: 28, years: '1913–1921', party: 'Democrat', born: 'Staunton, VA (associated with NJ)' },
  ],
  'New York': [
    { name: 'Donald Trump', number: 45 & 47, years: '2017–2021 & 2025–', party: 'Republican', born: 'Queens, NY' },
    { name: 'Franklin D. Roosevelt', number: 32, years: '1933–1945', party: 'Democrat', born: 'Hyde Park, NY' },
    { name: 'Theodore Roosevelt', number: 26, years: '1901–1909', party: 'Republican', born: 'New York City, NY' },
    { name: 'Millard Fillmore', number: 13, years: '1850–1853', party: 'Whig', born: 'Summerhill, NY' },
    { name: 'Martin Van Buren', number: 8, years: '1837–1841', party: 'Democrat', born: 'Kinderhook, NY' },
    { name: 'Chester Arthur', number: 21, years: '1881–1885', party: 'Republican', born: 'Fairfield, VT (associated with NY)' },
    { name: 'James K. Polk', number: 11, years: '1845–1849', party: 'Democrat', born: 'Pineville, NC (represented NY)' },
  ],
  'North Carolina': [
    { name: 'James K. Polk', number: 11, years: '1845–1849', party: 'Democrat', born: 'Pineville, NC' },
    { name: 'Andrew Johnson', number: 17, years: '1865–1869', party: 'Democrat', born: 'Raleigh, NC' },
  ],
  'Ohio': [
    { name: 'Ulysses S. Grant', number: 18, years: '1869–1877', party: 'Republican', born: 'Point Pleasant, OH' },
    { name: 'Rutherford B. Hayes', number: 19, years: '1877–1881', party: 'Republican', born: 'Delaware, OH' },
    { name: 'James A. Garfield', number: 20, years: '1881', party: 'Republican', born: 'Moreland Hills, OH' },
    { name: 'Benjamin Harrison', number: 23, years: '1889–1893', party: 'Republican', born: 'North Bend, OH' },
    { name: 'William McKinley', number: 25, years: '1897–1901', party: 'Republican', born: 'Niles, OH' },
    { name: 'William Howard Taft', number: 27, years: '1909–1913', party: 'Republican', born: 'Cincinnati, OH' },
    { name: 'Warren G. Harding', number: 29, years: '1921–1923', party: 'Republican', born: 'Blooming Grove, OH' },
  ],
  'Pennsylvania': [
    { name: 'James Buchanan', number: 15, years: '1857–1861', party: 'Democrat', born: 'Cove Gap, PA' },
    { name: 'Joe Biden', number: 46, years: '2021–2025', party: 'Democrat', born: 'Scranton, PA' },
  ],
  'South Carolina': [
    { name: 'Andrew Jackson', number: 7, years: '1829–1837', party: 'Democrat', born: 'Waxhaw, SC' },
    { name: 'James K. Polk', number: 11, years: '1845–1849', party: 'Democrat', born: 'Pineville, NC (SC heritage)' },
  ],
  'Tennessee': [
    { name: 'Andrew Jackson', number: 7, years: '1829–1837', party: 'Democrat', born: 'Waxhaw, SC (represented TN)' },
    { name: 'James K. Polk', number: 11, years: '1845–1849', party: 'Democrat', born: 'Pineville, NC (represented TN)' },
    { name: 'Andrew Johnson', number: 17, years: '1865–1869', party: 'Democrat', born: 'Raleigh, NC (represented TN)' },
    { name: 'Al Gore', number: null, years: 'Vice President 1993–2001', party: 'Democrat', born: 'Washington DC (raised in TN)' },
  ],
  'Texas': [
    { name: 'Dwight D. Eisenhower', number: 34, years: '1953–1961', party: 'Republican', born: 'Denison, TX' },
    { name: 'Lyndon B. Johnson', number: 36, years: '1963–1969', party: 'Democrat', born: 'Stonewall, TX' },
    { name: 'George W. Bush', number: 43, years: '2001–2009', party: 'Republican', born: 'New Haven, CT (associated with TX)' },
  ],
  'Vermont': [
    { name: 'Chester Arthur', number: 21, years: '1881–1885', party: 'Republican', born: 'Fairfield, VT' },
    { name: 'Calvin Coolidge', number: 30, years: '1923–1929', party: 'Republican', born: 'Plymouth Notch, VT' },
  ],
  'Virginia': [
    { name: 'George Washington', number: 1, years: '1789–1797', party: 'Unaffiliated', born: 'Westmoreland County, VA' },
    { name: 'Thomas Jefferson', number: 3, years: '1801–1809', party: 'Democratic-Republican', born: 'Shadwell, VA' },
    { name: 'James Madison', number: 4, years: '1809–1817', party: 'Democratic-Republican', born: 'Port Conway, VA' },
    { name: 'James Monroe', number: 5, years: '1817–1825', party: 'Democratic-Republican', born: 'Monroe Hall, VA' },
    { name: 'William Henry Harrison', number: 9, years: '1841', party: 'Whig', born: 'Charles City County, VA' },
    { name: 'John Tyler', number: 10, years: '1841–1845', party: 'Whig', born: 'Charles City County, VA' },
    { name: 'Zachary Taylor', number: 12, years: '1849–1850', party: 'Whig', born: 'Barboursville, VA' },
    { name: 'Woodrow Wilson', number: 28, years: '1913–1921', party: 'Democrat', born: 'Staunton, VA' },
  ],
  'Alabama': [],
  'Alaska': [],
  'Arizona': [],
  'Colorado': [],
  'Connecticut': [],
  'Delaware': [],
  'Florida': [],
  'Idaho': [],
  'Indiana': [],
  'Iowa': [],
  'Louisiana': [],
  'Maine': [],
  'Maryland': [],
  'Michigan': [],
  'Minnesota': [],
  'Mississippi': [],
  'Montana': [],
  'Nevada': [],
  'New Mexico': [],
  'North Dakota': [],
  'Oklahoma': [],
  'Oregon': [],
  'Rhode Island': [],
  'South Dakota': [],
  'Utah': [],
  'Washington': [],
  'West Virginia': [],
  'Wisconsin': [],
  'Wyoming': [],
}
