export const STATE_THEMES = {
  'Alabama': { from: '#1a3a5c', to: '#0f2339', accent: '#3b82f6', light: '#dbeafe', text: '#1e40af' },
  'Alaska': { from: '#1e3a5f', to: '#0f2340', accent: '#60a5fa', light: '#dbeafe', text: '#1e40af' },
  'Arizona': { from: '#92400e', to: '#78350f', accent: '#f59e0b', light: '#fef3c7', text: '#92400e' },
  'Arkansas': { from: '#14532d', to: '#052e16', accent: '#22c55e', light: '#dcfce7', text: '#166534' },
  'California': { from: '#b45309', to: '#92400e', accent: '#f59e0b', light: '#fef3c7', text: '#92400e' },
  'Colorado': { from: '#312e81', to: '#1e1b4b', accent: '#818cf8', light: '#e0e7ff', text: '#3730a3' },
  'Connecticut': { from: '#1e3a5f', to: '#0f2340', accent: '#3b82f6', light: '#dbeafe', text: '#1e40af' },
  'Delaware': { from: '#1e40af', to: '#1e3a8a', accent: '#60a5fa', light: '#dbeafe', text: '#1e40af' },
  'Florida': { from: '#0284c7', to: '#075985', accent: '#38bdf8', light: '#e0f2fe', text: '#0369a1' },
  'Georgia': { from: '#166534', to: '#14532d', accent: '#4ade80', light: '#dcfce7', text: '#166534' },
  'Hawaii': { from: '#0e7490', to: '#164e63', accent: '#22d3ee', light: '#cffafe', text: '#0e7490' },
  'Idaho': { from: '#365314', to: '#1a2e05', accent: '#84cc16', light: '#ecfccb', text: '#365314' },
  'Illinois': { from: '#1e3a5f', to: '#0f2340', accent: '#3b82f6', light: '#dbeafe', text: '#1e40af' },
  'Indiana': { from: '#1e1b4b', to: '#12104a', accent: '#818cf8', light: '#e0e7ff', text: '#3730a3' },
  'Iowa': { from: '#365314', to: '#1a2e05', accent: '#84cc16', light: '#ecfccb', text: '#365314' },
  'Kansas': { from: '#713f12', to: '#451a03', accent: '#f59e0b', light: '#fef3c7', text: '#92400e' },
  'Kentucky': { from: '#14532d', to: '#052e16', accent: '#4ade80', light: '#dcfce7', text: '#166534' },
  'Louisiana': { from: '#134e4a', to: '#042f2e', accent: '#2dd4bf', light: '#ccfbf1', text: '#0f766e' },
  'Maine': { from: '#1e3a5f', to: '#0f2340', accent: '#60a5fa', light: '#dbeafe', text: '#1e40af' },
  'Maryland': { from: '#7f1d1d', to: '#450a0a', accent: '#f87171', light: '#fee2e2', text: '#991b1b' },
  'Massachusetts': { from: '#1e3a5f', to: '#0f2340', accent: '#3b82f6', light: '#dbeafe', text: '#1e40af' },
  'Michigan': { from: '#0c4a6e', to: '#082f49', accent: '#38bdf8', light: '#e0f2fe', text: '#0369a1' },
  'Minnesota': { from: '#1e3a5f', to: '#0f2340', accent: '#60a5fa', light: '#dbeafe', text: '#1e40af' },
  'Mississippi': { from: '#14532d', to: '#052e16', accent: '#4ade80', light: '#dcfce7', text: '#166534' },
  'Missouri': { from: '#7f1d1d', to: '#450a0a', accent: '#f87171', light: '#fee2e2', text: '#991b1b' },
  'Montana': { from: '#1c3d5a', to: '#0f2535', accent: '#7dd3fc', light: '#e0f2fe', text: '#0369a1' },
  'Nebraska': { from: '#713f12', to: '#451a03', accent: '#fbbf24', light: '#fef3c7', text: '#92400e' },
  'Nevada': { from: '#78350f', to: '#451a03', accent: '#fb923c', light: '#ffedd5', text: '#9a3412' },
  'New Hampshire': { from: '#14532d', to: '#052e16', accent: '#4ade80', light: '#dcfce7', text: '#166534' },
  'New Jersey': { from: '#1e3a5f', to: '#0f2340', accent: '#3b82f6', light: '#dbeafe', text: '#1e40af' },
  'New Mexico': { from: '#7c2d12', to: '#431407', accent: '#fb923c', light: '#ffedd5', text: '#9a3412' },
  'New York': { from: '#1e293b', to: '#0f172a', accent: '#94a3b8', light: '#f1f5f9', text: '#334155' },
  'North Carolina': { from: '#1e3a5f', to: '#0f2340', accent: '#60a5fa', light: '#dbeafe', text: '#1e40af' },
  'North Dakota': { from: '#365314', to: '#1a2e05', accent: '#84cc16', light: '#ecfccb', text: '#365314' },
  'Ohio': { from: '#7f1d1d', to: '#450a0a', accent: '#f87171', light: '#fee2e2', text: '#991b1b' },
  'Oklahoma': { from: '#7c2d12', to: '#431407', accent: '#fb923c', light: '#ffedd5', text: '#9a3412' },
  'Oregon': { from: '#14532d', to: '#052e16', accent: '#4ade80', light: '#dcfce7', text: '#166534' },
  'Pennsylvania': { from: '#1e3a5f', to: '#0f2340', accent: '#3b82f6', light: '#dbeafe', text: '#1e40af' },
  'Rhode Island': { from: '#1e3a5f', to: '#0f2340', accent: '#60a5fa', light: '#dbeafe', text: '#1e40af' },
  'South Carolina': { from: '#14532d', to: '#052e16', accent: '#4ade80', light: '#dcfce7', text: '#166534' },
  'South Dakota': { from: '#713f12', to: '#451a03', accent: '#fbbf24', light: '#fef3c7', text: '#92400e' },
  'Tennessee': { from: '#1e3a5f', to: '#0f2340', accent: '#3b82f6', light: '#dbeafe', text: '#1e40af' },
  'Texas': { from: '#713f12', to: '#451a03', accent: '#fbbf24', light: '#fef3c7', text: '#92400e' },
  'Utah': { from: '#7c2d12', to: '#431407', accent: '#fb923c', light: '#ffedd5', text: '#9a3412' },
  'Vermont': { from: '#14532d', to: '#052e16', accent: '#4ade80', light: '#dcfce7', text: '#166534' },
  'Virginia': { from: '#1e3a5f', to: '#0f2340', accent: '#60a5fa', light: '#dbeafe', text: '#1e40af' },
  'Washington': { from: '#14532d', to: '#052e16', accent: '#4ade80', light: '#dcfce7', text: '#166534' },
  'West Virginia': { from: '#14532d', to: '#052e16', accent: '#4ade80', light: '#dcfce7', text: '#166534' },
  'Wisconsin': { from: '#0c4a6e', to: '#082f49', accent: '#38bdf8', light: '#e0f2fe', text: '#0369a1' },
  'Wyoming': { from: '#1c3d5a', to: '#0f2535', accent: '#7dd3fc', light: '#e0f2fe', text: '#0369a1' },
}

export function getStateFlag(stateCode) {
  // Using statesymbolsusa.org flag images — reliable public domain state flags
  const flags = {
    'AL': 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Alabama.svg',
    'AK': 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Alaska.svg',
    'AZ': 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arizona.svg',
    'AR': 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arkansas.svg',
    'CA': 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_California.svg',
    'CO': 'https://upload.wikimedia.org/wikipedia/commons/4/46/Flag_of_Colorado.svg',
    'CT': 'https://upload.wikimedia.org/wikipedia/commons/9/96/Flag_of_Connecticut.svg',
    'DE': 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Flag_of_Delaware.svg',
    'FL': 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Florida.svg',
    'GA': 'https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Georgia_%28U.S._state%29.svg',
    'HI': 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Hawaii.svg',
    'ID': 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_Idaho.svg',
    'IL': 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Illinois.svg',
    'IN': 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Flag_of_Indiana.svg',
    'IA': 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Iowa.svg',
    'KS': 'https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Kansas.svg',
    'KY': 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Flag_of_Kentucky.svg',
    'LA': 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Flag_of_Louisiana.svg',
    'ME': 'https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_Maine.svg',
    'MD': 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Maryland.svg',
    'MA': 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Massachusetts.svg',
    'MI': 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Flag_of_Michigan.svg',
    'MN': 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Minnesota.svg',
    'MS': 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Mississippi.svg',
    'MO': 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Flag_of_Missouri.svg',
    'MT': 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_Montana.svg',
    'NE': 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Flag_of_Nebraska.svg',
    'NV': 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Flag_of_Nevada.svg',
    'NH': 'https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_New_Hampshire.svg',
    'NJ': 'https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_New_Jersey.svg',
    'NM': 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_New_Mexico.svg',
    'NY': 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_New_York.svg',
    'NC': 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Flag_of_North_Carolina.svg',
    'ND': 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Flag_of_North_Dakota.svg',
    'OH': 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Ohio.svg',
    'OK': 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Oklahoma.svg',
    'OR': 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Oregon.svg',
    'PA': 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Pennsylvania.svg',
    'RI': 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Rhode_Island.svg',
    'SC': 'https://upload.wikimedia.org/wikipedia/commons/6/69/Flag_of_South_Carolina.svg',
    'SD': 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_South_Dakota.svg',
    'TN': 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Tennessee.svg',
    'TX': 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg',
    'UT': 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Utah.svg',
    'VT': 'https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Vermont.svg',
    'VA': 'https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Virginia.svg',
    'WA': 'https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Washington.svg',
    'WV': 'https://upload.wikimedia.org/wikipedia/commons/2/22/Flag_of_West_Virginia.svg',
    'WI': 'https://upload.wikimedia.org/wikipedia/commons/2/22/Flag_of_Wisconsin.svg',
    'WY': 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Wyoming.svg',
  }
  return flags[stateCode] || flags['FL']
}
