export const STATE_FACTS = {
  'Alabama': {
    code: 'AL',
    nickname: 'The Heart of Dixie',
    capital: 'Montgomery',
    population: '5,108,468',
    founded: 'December 14, 1819',
    statehood: 22,
    bird: 'Northern Flicker (Yellowhammer)',
    flower: 'Camellia',
    tree: 'Longleaf Pine',
    motto: 'Audemus jura nostra defendere (We dare defend our rights)',
    funFact: 'Alabama was the first state to declare Christmas a legal holiday in 1836.',
    celebrities: ['Helen Keller', 'Rosa Parks', 'Hank Aaron', 'Harper Lee', 'Lionel Richie'],
    electoralVotes: 9,
  },
  'Alaska': {
    code: 'AK',
    nickname: 'The Last Frontier',
    capital: 'Juneau',
    population: '733,583',
    founded: 'January 3, 1959',
    statehood: 49,
    bird: 'Willow Ptarmigan',
    flower: 'Forget-Me-Not',
    tree: 'Sitka Spruce',
    motto: 'North to the Future',
    funFact: 'Alaska has more coastline than all other U.S. states combined.',
    celebrities: ['Jewel', 'Carlos Boozer', 'Curt Schilling'],
    electoralVotes: 3,
  },
  'Arizona': {
    code: 'AZ',
    nickname: 'The Grand Canyon State',
    capital: 'Phoenix',
    population: '7,431,344',
    founded: 'February 14, 1912',
    statehood: 48,
    bird: 'Cactus Wren',
    flower: 'Saguaro Cactus Blossom',
    tree: 'Palo Verde',
    motto: 'Ditat Deus (God Enriches)',
    funFact: 'The Grand Canyon is one mile deep and 277 miles long.',
    celebrities: ['Emma Stone', 'Alice Cooper', 'Steven Spielberg', 'Stevie Nicks'],
    electoralVotes: 11,
  },
  'Arkansas': {
    code: 'AR',
    nickname: 'The Natural State',
    capital: 'Little Rock',
    population: '3,067,732',
    founded: 'June 15, 1836',
    statehood: 25,
    bird: 'Mockingbird',
    flower: 'Apple Blossom',
    tree: 'Loblolly Pine',
    motto: 'Regnat Populus (The People Rule)',
    funFact: 'Arkansas is the only state in the U.S. where diamonds are mined commercially.',
    celebrities: ['Johnny Cash', 'Bill Clinton', 'John Grisham', 'Walmart founder Sam Walton'],
    electoralVotes: 6,
  },
  'California': {
    code: 'CA',
    nickname: 'The Golden State',
    capital: 'Sacramento',
    population: '38,965,193',
    founded: 'September 9, 1850',
    statehood: 31,
    bird: 'California Quail',
    flower: 'Golden Poppy',
    tree: 'Coast Redwood',
    motto: 'Eureka (I have found it)',
    funFact: 'California has the largest economy of any U.S. state — larger than most countries.',
    celebrities: ['Leonardo DiCaprio', 'Marilyn Monroe', 'Steve Jobs', 'Serena Williams', 'Richard Nixon'],
    electoralVotes: 54,
  },
  'Colorado': {
    code: 'CO',
    nickname: 'The Centennial State',
    capital: 'Denver',
    population: '5,877,610',
    founded: 'August 1, 1876',
    statehood: 38,
    bird: 'Lark Bunting',
    flower: 'Rocky Mountain Columbine',
    tree: 'Colorado Blue Spruce',
    motto: 'Nil sine numine (Nothing without Providence)',
    funFact: 'Colorado has more than 300 days of sunshine per year — more than Miami or Los Angeles.',
    celebrities: ['Tim Allen', 'Chauncey Billups', 'Trey Parker', 'Jack Dempsey'],
    electoralVotes: 10,
  },
  'Connecticut': {
    code: 'CT',
    nickname: 'The Constitution State',
    capital: 'Hartford',
    population: '3,617,176',
    founded: 'January 9, 1788',
    statehood: 5,
    bird: 'American Robin',
    flower: 'Mountain Laurel',
    tree: 'White Oak',
    motto: 'Qui transtulit sustinet (He who transplanted still sustains)',
    funFact: 'The first hamburger in America was served in New Haven, Connecticut in 1900.',
    celebrities: ['Katharine Hepburn', 'Paul Newman', 'Mark Twain', 'George W. Bush'],
    electoralVotes: 7,
  },
  'Delaware': {
    code: 'DE',
    nickname: 'The First State',
    capital: 'Dover',
    population: '1,031,890',
    founded: 'December 7, 1787',
    statehood: 1,
    bird: 'Delaware Blue Hen',
    flower: 'Peach Blossom',
    tree: 'American Holly',
    motto: 'Liberty and Independence',
    funFact: 'Delaware was the first state to ratify the U.S. Constitution, earning it the nickname "The First State."',
    celebrities: ['Joe Biden', 'Ryan Phillippe', 'Aubrey Plaza', 'Elisabeth Shue'],
    electoralVotes: 3,
  },
  'Florida': {
    code: 'FL',
    nickname: 'The Sunshine State',
    capital: 'Tallahassee',
    population: '22,610,726',
    founded: 'March 3, 1845',
    statehood: 27,
    bird: 'Mockingbird',
    flower: 'Orange Blossom',
    tree: 'Sabal Palm',
    motto: 'In God We Trust',
    funFact: 'Florida has more golf courses than any other state in the U.S.',
    celebrities: ['Dwyane Wade', 'Flea', 'Pat Riley', 'Sidney Poitier', 'Jim Morrison'],
    electoralVotes: 30,
  },
  'Georgia': {
    code: 'GA',
    nickname: 'The Peach State',
    capital: 'Atlanta',
    population: '11,029,227',
    founded: 'January 2, 1788',
    statehood: 4,
    bird: 'Brown Thrasher',
    flower: 'Cherokee Rose',
    tree: 'Southern Live Oak',
    motto: 'Wisdom, Justice, and Moderation',
    funFact: 'Georgia is the largest state east of the Mississippi River.',
    celebrities: ['Martin Luther King Jr.', 'Ray Charles', 'Jimmy Carter', 'Usher', 'Julia Roberts'],
    electoralVotes: 16,
  },
  'Hawaii': {
    code: 'HI',
    nickname: 'The Aloha State',
    capital: 'Honolulu',
    population: '1,435,138',
    founded: 'August 21, 1959',
    statehood: 50,
    bird: 'Nene (Hawaiian Goose)',
    flower: 'Pua Aloalo (Yellow Hibiscus)',
    tree: 'Kukui (Candlenut)',
    motto: 'Ua Mau ke Ea o ka ʻĀina i ka Pono (The life of the land is perpetuated in righteousness)',
    funFact: 'Hawaii is the only U.S. state that grows coffee commercially.',
    celebrities: ['Barack Obama', 'Bruno Mars', 'Nicole Kidman', 'Bette Midler'],
    electoralVotes: 4,
  },
  'Idaho': {
    code: 'ID',
    nickname: 'The Gem State',
    capital: 'Boise',
    population: '1,964,726',
    founded: 'July 3, 1890',
    statehood: 43,
    bird: 'Mountain Bluebird',
    flower: 'Syringa (Mock Orange)',
    tree: 'Western White Pine',
    motto: 'Esto Perpetua (Let it be perpetual)',
    funFact: 'Idaho produces about one-third of all potatoes grown in the United States.',
    celebrities: ['Ezra Pound', 'Lana Turner', 'Gutzon Borglum'],
    electoralVotes: 4,
  },
  'Illinois': {
    code: 'IL',
    nickname: 'The Prairie State',
    capital: 'Springfield',
    population: '12,549,689',
    founded: 'December 3, 1818',
    statehood: 21,
    bird: 'Northern Cardinal',
    flower: 'Violet',
    tree: 'White Oak',
    motto: 'State Sovereignty, National Union',
    funFact: 'Chicago is known as the Windy City — but not because of the weather. The nickname came from boastful politicians.',
    celebrities: ['Barack Obama', 'Walt Disney', 'Kanye West', 'Harrison Ford', 'Oprah Winfrey'],
    electoralVotes: 19,
  },
  'Indiana': {
    code: 'IN',
    nickname: 'The Hoosier State',
    capital: 'Indianapolis',
    population: '6,862,199',
    founded: 'December 11, 1816',
    statehood: 19,
    bird: 'Northern Cardinal',
    flower: 'Peony',
    tree: 'Tulip Tree',
    motto: 'The Crossroads of America',
    funFact: 'Indiana has more miles of interstate highway per square mile than any other state.',
    celebrities: ['Michael Jackson', 'James Dean', 'David Letterman', 'Benjamin Harrison'],
    electoralVotes: 11,
  },
  'Iowa': {
    code: 'IA',
    nickname: 'The Hawkeye State',
    capital: 'Des Moines',
    population: '3,207,004',
    founded: 'December 28, 1846',
    statehood: 29,
    bird: 'American Goldfinch',
    flower: 'Wild Prairie Rose',
    tree: 'Bur Oak',
    motto: 'Our liberties we prize and our rights we will maintain',
    funFact: 'Iowa produces more corn than any other state and is a top producer of soybeans and pork.',
    celebrities: ['John Wayne', 'Ashton Kutcher', 'Tom Arnold', 'Grant Wood'],
    electoralVotes: 6,
  },
  'Kansas': {
    code: 'KS',
    nickname: 'The Sunflower State',
    capital: 'Topeka',
    population: '2,940,865',
    founded: 'January 29, 1861',
    statehood: 34,
    bird: 'Western Meadowlark',
    flower: 'Sunflower',
    tree: 'Cottonwood',
    motto: 'Ad astra per aspera (To the stars through difficulties)',
    funFact: 'The geographic center of the contiguous United States is located in Kansas.',
    celebrities: ['Dwight D. Eisenhower', 'Amelia Earhart', 'Buster Keaton', 'Melissa Etheridge'],
    electoralVotes: 6,
  },
  'Kentucky': {
    code: 'KY',
    nickname: 'The Bluegrass State',
    capital: 'Frankfort',
    population: '4,526,154',
    founded: 'June 1, 1792',
    statehood: 15,
    bird: 'Northern Cardinal',
    flower: 'Goldenrod',
    tree: 'Tulip Poplar',
    motto: 'United we stand, divided we fall',
    funFact: 'Kentucky has more miles of navigable waterways than any other state except Alaska.',
    celebrities: ['Muhammad Ali', 'George Clooney', 'Johnny Depp', 'Abraham Lincoln'],
    electoralVotes: 8,
  },
  'Louisiana': {
    code: 'LA',
    nickname: 'The Pelican State',
    capital: 'Baton Rouge',
    population: '4,573,749',
    founded: 'April 30, 1812',
    statehood: 18,
    bird: 'Brown Pelican',
    flower: 'Magnolia',
    tree: 'Bald Cypress',
    motto: 'Union, Justice, and Confidence',
    funFact: 'Louisiana is the only state that has parishes instead of counties.',
    celebrities: ['Britney Spears', 'Ellen DeGeneres', 'Tyler Perry', 'Lil Wayne', 'Louis Armstrong'],
    electoralVotes: 8,
  },
  'Maine': {
    code: 'ME',
    nickname: 'The Pine Tree State',
    capital: 'Augusta',
    population: '1,395,722',
    founded: 'March 15, 1820',
    statehood: 23,
    bird: 'Black-capped Chickadee',
    flower: 'White Pine Cone and Tassel',
    tree: 'Eastern White Pine',
    motto: 'Dirigo (I lead)',
    funFact: 'Maine is the only state that borders only one other state.',
    celebrities: ['Stephen King', 'Patrick Dempsey', 'Hannibal Hamlin'],
    electoralVotes: 4,
  },
  'Maryland': {
    code: 'MD',
    nickname: 'The Old Line State',
    capital: 'Annapolis',
    population: '6,180,253',
    founded: 'April 28, 1788',
    statehood: 7,
    bird: 'Baltimore Oriole',
    flower: 'Black-Eyed Susan',
    tree: 'White Oak',
    motto: 'Fatti maschii, parole femine (Manly deeds, womanly words)',
    funFact: 'Maryland is home to the U.S. Naval Academy, founded in 1845.',
    celebrities: ['Frederick Douglass', 'Babe Ruth', 'Frank Zappa', 'David Hasselhoff'],
    electoralVotes: 10,
  },
  'Massachusetts': {
    code: 'MA',
    nickname: 'The Bay State',
    capital: 'Boston',
    population: '7,001,399',
    founded: 'February 6, 1788',
    statehood: 6,
    bird: 'Black-capped Chickadee',
    flower: 'Mayflower',
    tree: 'American Elm',
    motto: 'Ense petit placidam sub libertate quietem (By the sword we seek peace, but peace only under liberty)',
    funFact: 'Massachusetts was home to the first public school in America, established in 1635.',
    celebrities: ['John F. Kennedy', 'Ben Affleck', 'Matt Damon', 'Mark Wahlberg', 'Conan O\'Brien'],
    electoralVotes: 11,
  },
  'Michigan': {
    code: 'MI',
    nickname: 'The Great Lakes State',
    capital: 'Lansing',
    population: '10,037,261',
    founded: 'January 26, 1837',
    statehood: 26,
    bird: 'American Robin',
    flower: 'Apple Blossom',
    tree: 'Eastern White Pine',
    motto: 'Si quaeris peninsulam amoenam circumspice (If you seek a pleasant peninsula, look about you)',
    funFact: 'Michigan is the only state that consists of two separate peninsulas.',
    celebrities: ['Eminem', 'Madonna', 'Magic Johnson', 'Stevie Wonder', 'Henry Ford'],
    electoralVotes: 15,
  },
  'Minnesota': {
    code: 'MN',
    nickname: 'The Land of 10,000 Lakes',
    capital: 'Saint Paul',
    population: '5,737,915',
    founded: 'May 11, 1858',
    statehood: 32,
    bird: 'Common Loon',
    flower: 'Pink and White Lady\'s Slipper',
    tree: 'Red Pine',
    motto: 'L\'Étoile du Nord (The Star of the North)',
    funFact: 'Minnesota actually has over 14,000 lakes — more than the nickname suggests.',
    celebrities: ['Prince', 'Bob Dylan', 'Judy Garland', 'Jessica Biel', 'Jesse Ventura'],
    electoralVotes: 10,
  },
  'Mississippi': {
    code: 'MS',
    nickname: 'The Magnolia State',
    capital: 'Jackson',
    population: '2,939,690',
    founded: 'December 10, 1817',
    statehood: 20,
    bird: 'Mockingbird',
    flower: 'Magnolia',
    tree: 'Magnolia',
    motto: 'Virtute et armis (By valor and arms)',
    funFact: 'Mississippi is the birthplace of the Blues music genre.',
    celebrities: ['Elvis Presley', 'Jim Henson', 'Morgan Freeman', 'Oprah Winfrey', 'B.B. King'],
    electoralVotes: 6,
  },
  'Missouri': {
    code: 'MO',
    nickname: 'The Show-Me State',
    capital: 'Jefferson City',
    population: '6,196,156',
    founded: 'August 10, 1821',
    statehood: 24,
    bird: 'Eastern Bluebird',
    flower: 'White Hawthorn Blossom',
    tree: 'Flowering Dogwood',
    motto: 'Salus populi suprema lex esto (The welfare of the people shall be the supreme law)',
    funFact: 'The ice cream cone was invented at the 1904 World\'s Fair in St. Louis, Missouri.',
    celebrities: ['Mark Twain', 'Harry Truman', 'Chuck Berry', 'Brad Pitt', 'Nelly'],
    electoralVotes: 10,
  },
  'Montana': {
    code: 'MT',
    nickname: 'Big Sky Country',
    capital: 'Helena',
    population: '1,132,812',
    founded: 'November 8, 1889',
    statehood: 41,
    bird: 'Western Meadowlark',
    flower: 'Bitterroot',
    tree: 'Ponderosa Pine',
    motto: 'Oro y Plata (Gold and Silver)',
    funFact: 'Montana has three times as many cattle as people.',
    celebrities: ['David Lynch', 'Gary Cooper', 'Dana Carvey', 'Evel Knievel'],
    electoralVotes: 4,
  },
  'Nebraska': {
    code: 'NE',
    nickname: 'The Cornhusker State',
    capital: 'Lincoln',
    population: '1,978,379',
    founded: 'March 1, 1867',
    statehood: 37,
    bird: 'Western Meadowlark',
    flower: 'Goldenrod',
    tree: 'Cottonwood',
    motto: 'Equality before the law',
    funFact: 'Nebraska is the only state with a unicameral (single chamber) legislature.',
    celebrities: ['Warren Buffett', 'Fred Astaire', 'Malcolm X', 'Johnny Carson'],
    electoralVotes: 5,
  },
  'Nevada': {
    code: 'NV',
    nickname: 'The Silver State',
    capital: 'Carson City',
    population: '3,194,176',
    founded: 'October 31, 1864',
    statehood: 36,
    bird: 'Mountain Bluebird',
    flower: 'Sagebrush',
    tree: 'Single-leaf Pinyon',
    motto: 'Battle Born',
    funFact: 'Nevada produces more gold than any other state and is one of the top gold producers in the world.',
    celebrities: ['Andre Agassi', 'Greg LeMond', 'Pat Nixon'],
    electoralVotes: 6,
  },
  'New Hampshire': {
    code: 'NH',
    nickname: 'The Granite State',
    capital: 'Concord',
    population: '1,402,054',
    founded: 'June 21, 1788',
    statehood: 9,
    bird: 'Purple Finch',
    flower: 'Purple Lilac',
    tree: 'White Birch',
    motto: 'Live Free or Die',
    funFact: 'New Hampshire holds the first primary election in every U.S. presidential race.',
    celebrities: ['Alan Shepard', 'Adam Sandler', 'Sarah Silverman', 'Dan Brown'],
    electoralVotes: 4,
  },
  'New Jersey': {
    code: 'NJ',
    nickname: 'The Garden State',
    capital: 'Trenton',
    population: '9,290,841',
    founded: 'December 18, 1787',
    statehood: 3,
    bird: 'Eastern Goldfinch',
    flower: 'Common Blue Violet',
    tree: 'Northern Red Oak',
    motto: 'Liberty and Prosperity',
    funFact: 'New Jersey is the most densely populated state in the U.S.',
    celebrities: ['Bruce Springsteen', 'Whitney Houston', 'Frank Sinatra', 'Jon Bon Jovi', 'Meryl Streep'],
    electoralVotes: 14,
  },
  'New Mexico': {
    code: 'NM',
    nickname: 'The Land of Enchantment',
    capital: 'Santa Fe',
    population: '2,114,371',
    founded: 'January 6, 1912',
    statehood: 47,
    bird: 'Greater Roadrunner',
    flower: 'Yucca Flower',
    tree: 'Piñon Pine',
    motto: 'Crescit eundo (It grows as it goes)',
    funFact: 'Santa Fe is the oldest capital city in the United States, founded in 1610.',
    celebrities: ['Neil Patrick Harris', 'Demi Moore', 'John Denver', 'William Hanna'],
    electoralVotes: 5,
  },
  'New York': {
    code: 'NY',
    nickname: 'The Empire State',
    capital: 'Albany',
    population: '19,571,216',
    founded: 'July 26, 1788',
    statehood: 11,
    bird: 'Eastern Bluebird',
    flower: 'Rose',
    tree: 'Sugar Maple',
    motto: 'Excelsior (Ever Upward)',
    funFact: 'New York City was the first capital of the United States under the Constitution.',
    celebrities: ['Jay-Z', 'Jennifer Lopez', 'Robert De Niro', 'Lady Gaga', 'Franklin D. Roosevelt'],
    electoralVotes: 28,
  },
  'North Carolina': {
    code: 'NC',
    nickname: 'The Tar Heel State',
    capital: 'Raleigh',
    population: '10,835,491',
    founded: 'November 21, 1789',
    statehood: 12,
    bird: 'Northern Cardinal',
    flower: 'Dogwood',
    tree: 'Longleaf Pine',
    motto: 'Esse quam videri (To be, rather than to seem)',
    funFact: 'The Wright Brothers made their first powered airplane flight at Kitty Hawk, North Carolina in 1903.',
    celebrities: ['Michael Jordan', 'James K. Polk', 'Ava Gardner', 'Zach Galifianakis', 'Clay Aiken'],
    electoralVotes: 16,
  },
  'North Dakota': {
    code: 'ND',
    nickname: 'The Peace Garden State',
    capital: 'Bismarck',
    population: '779,261',
    founded: 'November 2, 1889',
    statehood: 39,
    bird: 'Western Meadowlark',
    flower: 'Wild Prairie Rose',
    tree: 'American Elm',
    motto: 'Liberty and union, now and forever, one and inseparable',
    funFact: 'North Dakota is the least visited state in the United States.',
    celebrities: ['Josh Duhamel', 'Lawrence Welk', 'Angie Dickinson'],
    electoralVotes: 3,
  },
  'Ohio': {
    code: 'OH',
    nickname: 'The Buckeye State',
    capital: 'Columbus',
    population: '11,785,935',
    founded: 'March 1, 1803',
    statehood: 17,
    bird: 'Northern Cardinal',
    flower: 'Scarlet Carnation',
    tree: 'Ohio Buckeye',
    motto: 'With God, all things are possible',
    funFact: 'Ohio has produced more U.S. presidents than any other state — 8 in total.',
    celebrities: ['LeBron James', 'Neil Armstrong', 'John Glenn', 'Steven Spielberg', 'Drew Carey'],
    electoralVotes: 17,
  },
  'Oklahoma': {
    code: 'OK',
    nickname: 'The Sooner State',
    capital: 'Oklahoma City',
    population: '4,053,824',
    founded: 'November 16, 1907',
    statehood: 46,
    bird: 'Scissor-tailed Flycatcher',
    flower: 'Mistletoe',
    tree: 'Eastern Redbud',
    motto: 'Labor omnia vincit (Labor conquers all things)',
    funFact: 'Oklahoma has more man-made lakes than any other state.',
    celebrities: ['Will Rogers', 'Garth Brooks', 'Blake Shelton', 'Chuck Norris', 'Ron Howard'],
    electoralVotes: 7,
  },
  'Oregon': {
    code: 'OR',
    nickname: 'The Beaver State',
    capital: 'Salem',
    population: '4,233,358',
    founded: 'February 14, 1859',
    statehood: 33,
    bird: 'Western Meadowlark',
    flower: 'Oregon Grape',
    tree: 'Douglas Fir',
    motto: 'Alis volat propriis (She flies with her own wings)',
    funFact: 'Oregon is the only state with a flag that has different images on each side.',
    celebrities: ['Tonya Harding', 'Matt Groening', 'Linus Pauling', 'Beverly Cleary'],
    electoralVotes: 8,
  },
  'Pennsylvania': {
    code: 'PA',
    nickname: 'The Keystone State',
    capital: 'Harrisburg',
    population: '12,961,683',
    founded: 'December 12, 1787',
    statehood: 2,
    bird: 'Ruffed Grouse',
    flower: 'Mountain Laurel',
    tree: 'Eastern Hemlock',
    motto: 'Virtue, Liberty and Independence',
    funFact: 'Pennsylvania is home to the first computer, ENIAC, built at the University of Pennsylvania in 1945.',
    celebrities: ['Will Smith', 'Taylor Swift', 'Kobe Bryant', 'Tina Fey', 'Benjamin Franklin'],
    electoralVotes: 19,
  },
  'Rhode Island': {
    code: 'RI',
    nickname: 'The Ocean State',
    capital: 'Providence',
    population: '1,095,962',
    founded: 'May 29, 1790',
    statehood: 13,
    bird: 'Rhode Island Red',
    flower: 'Violet',
    tree: 'Red Maple',
    motto: 'Hope',
    funFact: 'Rhode Island is the smallest state in the U.S. but has the longest official name: "State of Rhode Island and Providence Plantations."',
    celebrities: ['H.P. Lovecraft', 'James Woods', 'Debra Messing', 'Seth MacFarlane'],
    electoralVotes: 4,
  },
  'South Carolina': {
    code: 'SC',
    nickname: 'The Palmetto State',
    capital: 'Columbia',
    population: '5,373,555',
    founded: 'May 23, 1788',
    statehood: 8,
    bird: 'Carolina Wren',
    flower: 'Yellow Jessamine',
    tree: 'Sabal Palmetto',
    motto: 'Animis opibusque parati (Prepared in mind and resources)',
    funFact: 'The first decisive American victory of the Revolutionary War was fought in South Carolina.',
    celebrities: ['Stephen Colbert', 'Darius Rucker', 'Eartha Kitt', 'Andrew Jackson'],
    electoralVotes: 9,
  },
  'South Dakota': {
    code: 'SD',
    nickname: 'The Mount Rushmore State',
    capital: 'Pierre',
    population: '919,318',
    founded: 'November 2, 1889',
    statehood: 40,
    bird: 'Ring-necked Pheasant',
    flower: 'Pasque Flower',
    tree: 'Black Hills Spruce',
    motto: 'Under God the people rule',
    funFact: 'Mount Rushmore took 14 years to carve and was never fully completed.',
    celebrities: ['Tom Brokaw', 'Sitting Bull', 'Crazy Horse', 'Mary Hart'],
    electoralVotes: 3,
  },
  'Tennessee': {
    code: 'TN',
    nickname: 'The Volunteer State',
    capital: 'Nashville',
    population: '7,126,489',
    founded: 'June 1, 1796',
    statehood: 16,
    bird: 'Mockingbird',
    flower: 'Iris',
    tree: 'Tulip Poplar',
    motto: 'Agriculture and Commerce',
    funFact: 'Tennessee is bordered by more states than any other — 8 states share its border.',
    celebrities: ['Dolly Parton', 'Elvis Presley', 'Justin Timberlake', 'Miley Cyrus', 'Morgan Freeman'],
    electoralVotes: 11,
  },
  'Texas': {
    code: 'TX',
    nickname: 'The Lone Star State',
    capital: 'Austin',
    population: '30,503,301',
    founded: 'December 29, 1845',
    statehood: 28,
    bird: 'Mockingbird',
    flower: 'Bluebonnet',
    tree: 'Pecan',
    motto: 'Friendship',
    funFact: 'Texas is the only state that was formerly an independent nation — the Republic of Texas.',
    celebrities: ['Beyoncé', 'Selena Gomez', 'Matthew McConaughey', 'George W. Bush', 'Janis Joplin'],
    electoralVotes: 40,
  },
  'Utah': {
    code: 'UT',
    nickname: 'The Beehive State',
    capital: 'Salt Lake City',
    population: '3,417,734',
    founded: 'January 4, 1896',
    statehood: 45,
    bird: 'California Gull',
    flower: 'Sego Lily',
    tree: 'Quaking Aspen',
    motto: 'Industry',
    funFact: 'The Great Salt Lake is the largest saltwater lake in the Western Hemisphere.',
    celebrities: ['Philo Farnsworth', 'Butch Cassidy', 'Roseanne Barr', 'The Osmonds'],
    electoralVotes: 6,
  },
  'Vermont': {
    code: 'VT',
    nickname: 'The Green Mountain State',
    capital: 'Montpelier',
    population: '647,464',
    founded: 'March 4, 1791',
    statehood: 14,
    bird: 'Hermit Thrush',
    flower: 'Red Clover',
    tree: 'Sugar Maple',
    motto: 'Freedom and Unity',
    funFact: 'Vermont produces more maple syrup than any other state in the U.S.',
    celebrities: ['Bernie Sanders', 'John Dewey', 'Rudy Vallee', 'Trey Anastasio'],
    electoralVotes: 3,
  },
  'Virginia': {
    code: 'VA',
    nickname: 'Old Dominion',
    capital: 'Richmond',
    population: '8,715,698',
    founded: 'June 25, 1788',
    statehood: 10,
    bird: 'Northern Cardinal',
    flower: 'American Dogwood',
    tree: 'Flowering Dogwood',
    motto: 'Sic semper tyrannis (Thus always to tyrants)',
    funFact: 'Virginia is called the "Mother of Presidents" — 8 U.S. presidents were born there.',
    celebrities: ['Pharrell Williams', 'Tim Reid', 'Missy Elliott', 'Thomas Jefferson', 'George Washington'],
    electoralVotes: 13,
  },
  'Washington': {
    code: 'WA',
    nickname: 'The Evergreen State',
    capital: 'Olympia',
    population: '7,812,880',
    founded: 'November 11, 1889',
    statehood: 42,
    bird: 'Willow Goldfinch',
    flower: 'Coast Rhododendron',
    tree: 'Western Hemlock',
    motto: 'Alki (By and by)',
    funFact: 'Washington state is the top apple-producing state in the U.S., growing about 70% of the nation\'s apples.',
    celebrities: ['Jimi Hendrix', 'Bill Gates', 'Jeff Bezos', 'Kenny G', 'Bing Crosby'],
    electoralVotes: 12,
  },
  'West Virginia': {
    code: 'WV',
    nickname: 'The Mountain State',
    capital: 'Charleston',
    population: '1,770,071',
    founded: 'June 20, 1863',
    statehood: 35,
    bird: 'Northern Cardinal',
    flower: 'Rhododendron',
    tree: 'Sugar Maple',
    motto: 'Montani semper liberi (Mountaineers are always free)',
    funFact: 'West Virginia is the only state formed by separating from another state during the Civil War.',
    celebrities: ['Chuck Yeager', 'Don Knotts', 'Brad Paisley', 'Jennifer Garner'],
    electoralVotes: 4,
  },
  'Wisconsin': {
    code: 'WI',
    nickname: 'The Badger State',
    capital: 'Madison',
    population: '5,910,955',
    founded: 'May 29, 1848',
    statehood: 30,
    bird: 'American Robin',
    flower: 'Wood Violet',
    tree: 'Sugar Maple',
    motto: 'Forward',
    funFact: 'Wisconsin produces about 25% of all cheese made in the United States.',
    celebrities: ['Orson Welles', 'Frank Lloyd Wright', 'Harry Houdini', 'Spencer Tracy', 'Liberace'],
    electoralVotes: 10,
  },
  'Wyoming': {
    code: 'WY',
    nickname: 'The Equality State',
    capital: 'Cheyenne',
    population: '584,057',
    founded: 'July 10, 1890',
    statehood: 44,
    bird: 'Western Meadowlark',
    flower: 'Indian Paintbrush',
    tree: 'Plains Cottonwood',
    motto: 'Equal Rights',
    funFact: 'Wyoming was the first state to grant women the right to vote, in 1869 — 50 years before the 19th Amendment.',
    celebrities: ['Dick Cheney', 'Jackson Pollock', 'Patricia MacLachlan'],
    electoralVotes: 3,
  },
}

export const STATE_NAMES = Object.keys(STATE_FACTS)
export const STATE_CODES = Object.fromEntries(
  Object.entries(STATE_FACTS).map(([name, data]) => [data.code, name])
)
